version: '3.9'
services:
  shipping_service:
    container_name: shipping_service
    build:
      context: /Users/younes/Downloads/shippingservice
      dockerfile: /Users/younes/Downloads/shippingservice/src/main/resources/Dockerfile
    depends_on:
      orders_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders_db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    ports:
      - 8080:8080

  orders_db:
    image: 'postgres:latest'
    container_name: orders_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5